export const supabaseUrl = 'https://zzaneglbcaviidinehsa.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6YW5lZ2xiY2F2aWlkaW5laHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjgyMDY0MDksImV4cCI6MjA0Mzc4MjQwOX0.pfPqShv-miGb0Hh1BF5JDrqa0ymfmEBzm_QsPF7YbIs';
